{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "namada-indexer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namada-indexer.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.argocd.deployment }}
    "argocd.argoproj.io/sync-wave": "-4"
    {{- else }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
