{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitcoind.fullname" . }}-auth
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
type: Opaque
data:
  rpcuser: {{ .Values.auth.username | b64enc | quote }}
  rpcpassword: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
