{{- if and .Values.auth.enabled (not .Values.externalSecrets.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitcoind.fullname" . }}-auth
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
type: Opaque
data:
  rpcpassword: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
