{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bitcoind.fullname" . }}-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStore }}
  target:
    name: {{ include "bitcoind.fullname" . }}-auth
    creationPolicy: Owner
  data:
    - secretKey: rpcpassword
      remoteRef:
        key: {{ .Values.externalSecrets.remoteSecretKey }}
{{- end }}
