apiVersion: v2
name: namada-indexer
description: A Helm chart for deploying a namada indexer
type: application
version: "1.0.1"
appVersion: "1.0"

dependencies:
  - name: postgres-operator
    version: "1.13.0"
    repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
    condition: postgresOperator.install.enabled
  - name: redis
    version: "20.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.install.enabled
