apiVersion: v1
kind: Pod
metadata:
  name: test-slack-secret
  namespace: cosmos-watcher
spec:
  containers:
  - name: test
    image: busybox
    command: ['sh', '-c', 'echo "Secret value is: $SLACK_WEBHOOK_URL" && sleep 3600']
    env:
    - name: SLACK_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: slack-webhook-url
          key: url
  restartPolicy: Never 