apiVersion: v1
kind: Pod
metadata:
  name: test-slack-webhook
  namespace: cosmos-watcher
spec:
  containers:
  - name: test
    image: curlimages/curl
    command: ['sh', '-c', 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"Hello from K8s test pod!\"}" "$SLACK_WEBHOOK_URL"']
    env:
    - name: SLACK_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: slack-webhook-url
          key: url
  restartPolicy: Never 