apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmos-exporter.fullname" . }}-config
  labels:
    {{- include "cosmos-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |-
    general:
      network: {{ .Values.config.general.network }}
      chain_id: {{ .Values.config.general.chain_id | default "cometbft" }}
      mode: {{ .Values.config.general.mode }}
      metrics:
        address: {{ .Values.config.general.metrics.address }}
        port: {{ .Values.config.general.metrics.port }}
        path: {{ .Values.config.general.metrics.path }}
      alerting:
        {{- if and .Values.config.general.alerting.validators (ne (len .Values.config.general.alerting.validators) 0) }}
        validators:
          {{- toYaml .Values.config.general.alerting.validators | nindent 10 }}
        {{- else }}
        validators: []
        {{- end }}
      nodes:
        rpc:
          {{- if and .Values.config.nodes.rpc (ne (len .Values.config.nodes.rpc) 0) }}
          {{- range .Values.config.nodes.rpc }}
          - name: {{ .name }}
            url: {{ .url }}
            healthEndpoint: {{ .healthEndpoint }}
          {{- end }}
          {{- else }}
          []
          {{- end }}
        lcd:
          {{- if and .Values.config.nodes.lcd (ne (len .Values.config.nodes.lcd) 0) }}
          {{- range .Values.config.nodes.lcd }}
          - name: {{ .name }}
            url: {{ .url }}
            healthEndpoint: {{ .healthEndpoint }}
          {{- end }}
          {{- else }}
          []
          {{- end }}

    node:
      client: {{ .Values.config.node.client }}
      tendermint:
        nodeInfo:
          enabled: {{ .Values.config.node.tendermint.nodeInfo.enabled }}
          interval: {{ .Values.config.node.tendermint.nodeInfo.interval }}
      cometbft:
        status:
          enabled: {{ .Values.config.node.cometbft.status.enabled }}
          interval: {{ .Values.config.node.cometbft.status.interval }}

    network:
      cometbft:
        validators:
          enabled: {{ .Values.config.network.cometbft.validators.enabled }}
          interval: {{ .Values.config.network.cometbft.validators.interval }}
        block:
          enabled: {{ .Values.config.network.cometbft.block.enabled }}
          interval: {{ .Values.config.network.cometbft.block.interval }}
          window: {{ .Values.config.network.cometbft.block.window }}
          tx:
            enabled: {{ .Values.config.network.cometbft.block.tx.enabled }}
          uptime:
            persistence: {{ .Values.config.network.cometbft.block.uptime.persistence }}

      tendermint:
        bank:
          {{- if and .Values.config.network.tendermint.bank.addresses (ne (len .Values.config.network.tendermint.bank.addresses) 0) }}
          addresses:
            {{- toYaml .Values.config.network.tendermint.bank.addresses | nindent 12 }}
          {{- else }}
          addresses: []
          {{- end }}
          enabled: {{ .Values.config.network.tendermint.bank.enabled }}
          interval: {{ .Values.config.network.tendermint.bank.interval }}
        distribution:
          enabled: {{ .Values.config.network.tendermint.distribution.enabled }}
          interval: {{ .Values.config.network.tendermint.distribution.interval }}
        gov:
          enabled: {{ .Values.config.network.tendermint.gov.enabled }}
          interval: {{ .Values.config.network.tendermint.gov.interval }}
        staking:
          enabled: {{ .Values.config.network.tendermint.staking.enabled }}
          interval: {{ .Values.config.network.tendermint.staking.interval }}
          validators: {{ .Values.config.network.tendermint.staking.validators | default true }}
          delegations: {{ .Values.config.network.tendermint.staking.delegations | default true }}
          commissions: {{ .Values.config.network.tendermint.staking.commissions | default true }}
          pool: {{ .Values.config.network.tendermint.staking.pool | default true }}
          params: {{ .Values.config.network.tendermint.staking.params | default true }}
        slashing:
          enabled: {{ .Values.config.network.tendermint.slashing.enabled }}
          interval: {{ .Values.config.network.tendermint.slashing.interval }}
        upgrade:
          enabled: {{ .Values.config.network.tendermint.upgrade.enabled }}
          interval: {{ .Values.config.network.tendermint.upgrade.interval }}

      mezo:
        poa:
          enabled: {{ .Values.config.network.mezo.poa.enabled }}
          interval: {{ .Values.config.network.mezo.poa.interval }}

      babylon:
        bls:
          enabled: {{ .Values.config.network.babylon.bls.enabled }}
          interval: {{ .Values.config.network.babylon.bls.interval }}

      lombard:
        ledger:
          {{- if and .Values.config.network.lombard.ledger.addresses (ne (len .Values.config.network.lombard.ledger.addresses) 0) }}
          addresses:
            {{- toYaml .Values.config.network.lombard.ledger.addresses | nindent 12 }}
          {{- else }}
          addresses: []
          {{- end }}
          enabled: {{ .Values.config.network.lombard.ledger.enabled }}
          interval: {{ .Values.config.network.lombard.ledger.interval }}

      namada:
        account:
          {{- if and .Values.config.network.namada.account.addresses (ne (len .Values.config.network.namada.account.addresses) 0) }}
          addresses:
            {{- toYaml .Values.config.network.namada.account.addresses | nindent 12 }}
          {{- else }}
          addresses: []
          {{- end }}
          enabled: {{ .Values.config.network.namada.account.enabled }}
          interval: {{ .Values.config.network.namada.account.interval }}
        pos:
          enabled: {{ .Values.config.network.namada.pos.enabled }}
          interval: {{ .Values.config.network.namada.pos.interval }}

      coredao:
        block:
          enabled: {{ .Values.config.network.coredao.block.enabled }}
          interval: {{ .Values.config.network.coredao.block.interval }}
          window: {{ .Values.config.network.coredao.block.window }}
        validator:
          enabled: {{ .Values.config.network.coredao.validator.enabled }}
          interval: {{ .Values.config.network.coredao.validator.interval }}
          api:
            enabled: {{ .Values.config.network.coredao.validator.api.enabled }}
            url: {{ .Values.config.network.coredao.validator.api.url }}
            api_key: {{ .Values.config.network.coredao.validator.api.api_key }}
            cache_duration_seconds: {{ .Values.config.network.coredao.validator.api.cache_duration_seconds }}
        staking:
          enabled: {{ .Values.config.network.coredao.staking.enabled }}
          interval: {{ .Values.config.network.coredao.staking.interval }}

      sei:
        validators:
          enabled: {{ .Values.config.network.sei.validators.enabled }}
          interval: {{ .Values.config.network.sei.validators.interval }}
        block:
          enabled: {{ .Values.config.network.sei.block.enabled }}
          interval: {{ .Values.config.network.sei.block.interval }}
          window: {{ .Values.config.network.sei.block.window }}
          tx:
            enabled: {{ .Values.config.network.sei.block.tx.enabled }}
          uptime:
            persistence: {{ .Values.config.network.sei.block.uptime.persistence }}
