---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Values.appName }}"
  labels:
    {{- include "cosmos-exporter.labels" $ | nindent 4 }}
    k8s-app: {{ $.Values.appName }}
spec:
  type: {{ $.Values.services.type | default "ClusterIP" }}
  ports:
  {{- toYaml $.Values.services.ports | nindent 2 }}
  selector:
    {{- include "cosmos-exporter.selectorLabels" $ | nindent 4 }}
    k8s-app: {{ $.Values.appName }}
