# Default values for allora-worker.

replicaCount: 1

# Container configurations
containers:
  # You can define multiple containers here
  main:
    image: ""
    ports:
      - name: http
        containerPort:
        protocol: TCP
    resources:
      requests:
        memory: ""
        cpu: ""
      limits:
        memory: ""
        cpu: ""
    command: []
    args: []
    livenessProbe: {}
    readinessProbe: {}
    volumeMounts: []
    env: []
    envFrom: []
    service:
      enabled: false
      type: ClusterIP
      port:
      targetPort:

imagePullSecrets: []

persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

# External Secrets configuration
externalSecrets: []
# - name:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name:
#   target:
#     name:
#     creationPolicy: Owner
#   data:
#   - secretKey:
#     remoteRef:
#       key:
#       property:

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Affinity settings
affinity: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Additional labels
labels: {}

# Pod annotations
podAnnotations: {}

# Service account
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Pod security context
podSecurityContext: {}

# Security context
securityContext: {}

# Image pull policy
imagePullPolicy: IfNotPresent

# Additional volumes
volumes: []

# Additional volumes
additionalVolumes: []

# Init containers
initContainers: {}

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

