apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "blch-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "blch-node.commonAnnotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - name: p2p
      port: {{ .Values.service.ports.p2p.port }}
      targetPort: p2p
      protocol: {{ .Values.service.ports.p2p.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.p2p.nodePort }}
      nodePort: {{ .Values.service.ports.p2p.nodePort }}
      {{- end }}
    - name: rpc
      port: {{ .Values.service.ports.rpc.port }}
      targetPort: rpc
      protocol: {{ .Values.service.ports.rpc.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.rpc.nodePort }}
      nodePort: {{ .Values.service.ports.rpc.nodePort }}
      {{- end }}
    - name: grpc
      port: {{ .Values.service.ports.grpc.port }}
      targetPort: grpc
      protocol: {{ .Values.service.ports.grpc.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.grpc.nodePort }}
      nodePort: {{ .Values.service.ports.grpc.nodePort }}
      {{- end }}
    - name: rest
      port: {{ .Values.service.ports.rest.port }}
      targetPort: rest
      protocol: {{ .Values.service.ports.rest.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.rest.nodePort }}
      nodePort: {{ .Values.service.ports.rest.nodePort }}
      {{- end }}
    - name: ws
      port: {{ .Values.service.ports.ws.port }}
      targetPort: ws
      protocol: {{ .Values.service.ports.ws.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.ws.nodePort }}
      nodePort: {{ .Values.service.ports.ws.nodePort }}
      {{- end }}
  selector:
    {{- include "blch-node.selectorLabels" . | nindent 4 }}
