{{- if .Values.vaultInjection.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blch-node.fullname" . }}
  labels:
    {{- include "blch-node.labels" . | nindent 4 }}
{{- end }}
