{{- if .Values.vaultStaticSecrets }}
{{- range .Values.vaultStaticSecrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if .vaultAuthRef }}
  vaultAuthRef: {{ .vaultAuthRef }}
  {{- end }}
  mount: {{ .mount }}
  type: {{ .type | default "kv-v2" }}
  path: {{ .path }}
  refreshAfter: {{ .refreshAfter | default "1h" }}
  destination:
    name: {{ .destination.name }}
    create: true
    type: Opaque
{{- end }}
{{- end }}
