{{- if .Values.basicAuth.enabled }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-basic-auth-creds" .Release.Name) }}
{{- if not $existingSecret }}
{{- $username := randAlphaNum 8 }}
{{- $password := randAlphaNum 16 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth-creds
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": HookFailed
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": HookFailed  
type: Opaque
data:
  auth: {{ htpasswd $username $password | b64enc | quote }}
{{- end }}
{{- end }}
