{{- if .Values.monitoring.enabled -}}
{{- if .Values.monitoring.alerts.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-rules
  labels:
    app: kube-prometheus-stack
spec:
  groups:
  - name: blockchain-alerts
    rules:
    - alert: BlockHeightDifferenceGrowing
      expr: |
        sum(chain_latest_block_height{cosmos_node="{{ .Release.Name }}", namespace="{{ .Release.Namespace }}", rpc_endpoint="{{ .Values.monitoring.publicRpcEndpoint }}"})
          - sum(chain_latest_block_height{cosmos_node="{{ .Release.Name }}", namespace="{{ .Release.Namespace }}", rpc_endpoint="{{ include "host" (dict "context" $ "endpointName" "rpc") }}"})
          > {{ .Values.monitoring.alerts.growingBlockHeightDifference }}
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
        pod: {{ .Release.Name }}
      annotations:
        summary: "Block height difference is growing for {{ .Release.Namespace }}/{{ .Release.Name }}"
        description: "{{ .Release.Name }} node in namespace {{ .Release.Namespace }} is more than {{ .Values.monitoring.alerts.growingBlockHeightDifference }} blocks behind the public RPC endpoint."
    - alert: BlockHeightDifferenceCritical
      expr: |
        sum(chain_latest_block_height{cosmos_node="{{ .Release.Name }}", namespace="{{ .Release.Namespace }}", rpc_endpoint="{{ .Values.monitoring.publicRpcEndpoint }}"})
          - sum(chain_latest_block_height{cosmos_node="{{ .Release.Name }}", namespace="{{ .Release.Namespace }}", rpc_endpoint="{{ include "host" (dict "context" $ "endpointName" "rpc") }}"})
          > {{ .Values.monitoring.alerts.maximumBlockHeightDifference }}   
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
        pod: {{ .Release.Name }}                
      annotations:
        summary: "Block height difference too high for {{ .Release.Namespace }}/{{ .Release.Name }}"
        description: "{{ .Release.Name }} node in namespace {{ .Release.Namespace }} is more than {{ .Values.monitoring.alerts.maximumBlockHeightDifference }} blocks behind the public RPC endpoint."
    - alert: CometBFTPeersDrop
      expr: |
        (cometbft_p2p_peers{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"} 
          - cometbft_p2p_peers{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"} offset 5m) 
          / cometbft_p2p_peers{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"} 
          * 100 > {{ .Values.monitoring.alerts.maximumPeerDropPercentage }}
      for: 5m
      labels:
        severity: info
      annotations:
        summary: "CometBFT P2P Peers Drop for {{ .Release.Name }} node in namespace {{ .Release.Namespace }}"
        description: "The number of P2P peers for {{ .Release.Name }} node in namespace {{ .Release.Namespace }} has dropped by more than 25% over the last 5 minutes."
    - alert: RpcEndpointDown
      expr: | 
        probe_http_status_code{
        rpc_endpoint="{{ include "host" (dict "context" $ "endpointName" "rpc") }}"} 
          < 200 
          or 
          probe_http_status_code{rpc_endpoint="{{ include "host" (dict "context" $ "endpointName" "rpc") }}"}
          >= 300
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "The RPC endpoint {{ include "host" (dict "context" $ "endpointName" "rpc") }} is down."
        description: "Endpoint for {{ .Release.Name }} node in namespace {{ .Release.Namespace }} has been down for the last 5 minutes."
{{- end -}}
{{- end -}}
