{{- if .Values.monitoring.enabled -}}
{{- if .Values.monitoring.alerts.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-rules
  labels:
    app: kube-prometheus-stack
spec:
  groups:
  - name: blockchain-alerts
    rules:
    - record: chain_block_height_diff
      expr: |
        label_replace(chain_latest_block_height{cosmos_node="{{ .Release.Name }}", namespace="{{ .Release.Namespace }}"}, "cosmos_node", "$1", "pod", "") 
          - on  (namespace) group_left(pod) 
          cometbft_consensus_height{pod=~"{{ .Release.Name }}-.?", namespace="{{ .Release.Namespace }}"}
      labels:
        cosmos_node: "{{ .Release.Name }}"
        namespace: "{{ .Release.Namespace }}"
    - alert: BlockHeightDifferenceGrowing
      expr: |
        chain_block_height_diff{cosmos_node="{{ .Release.Name }}", namespace="{{ .Release.Namespace }}"} > {{ .Values.monitoring.alerts.growingBlockHeightDifference }}   
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Block height difference is growing for chain {{ .Values.blch.id }}"
        description: "{{ .Release.Name }} node for chain {{ .Values.blch.id }} in namespace {{ .Values.namespace }} is more than {{ .Values.monitoring.alerts.growingBlockHeightDifference }} blocks behind the public RPC endpoint."        
    - alert: BlockHeightDifferenceCritical
      expr: |
        chain_block_height_diff{cosmos_node="{{ .Release.Name }}", namespace="{{ .Release.Namespace }}"} > {{ .Values.monitoring.alerts.maximumBlockHeightDifference }}   
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Block height difference too high for chain {{ .Values.blch.id }}"
        description: "{{ .Release.Name }} node for chain {{ .Values.blch.id }} in namespace {{ .Values.namespace }} is more than {{ .Values.monitoring.alerts.maximumBlockHeightDifference }} blocks behind the public RPC endpoint."
    - alert: CometBFTPeersDrop
      expr: |
        (cometbft_p2p_peers{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"} 
          - cometbft_p2p_peers{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"} offset 5m) 
          / cometbft_p2p_peers{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"} 
          * 100 > {{ .Values.monitoring.alerts.maximumPeerDropPercentage }}
      for: 5m
      labels:
        severity: info
      annotations:
        summary: "CometBFT P2P Peers Drop for {{`$labels.chain_id`}}"
        description: "The number of P2P peers for chain {{`$labels.chain_id`}} in {{`$labels.namespace`}}/{{`$labels.pod`}} has dropped by more than 25% over the last 5 minutes."
    - alert: LowTxSuccessRate
      expr: |
        cometbft_consensus_total_txs{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"} 
        - cometbft_mempool_failed_txs{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"} 
          / cometbft_consensus_total_txs{pod=~"{{ .Release.Name }}-.*", namespace="{{ .Release.Namespace }}"}
          * 100 < {{ .Values.monitoring.alerts.txSuccessRateThreshold }}
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Failed TXs for {{`$labels.pod`}}"
        description: "Transaction success rate is below the SLO for {{`$labels.chain_id`}} in {{`$labels.namespace`}} /{{`$labels.pod`}}."
    - alert: RpcSvcDown
      expr: | 
        probe_http_status_code{
        rpc_svc="{{ .Release.Name }}-rpc.{{ .Release.Namespace }}"} 
          < 200 
          or 
          probe_http_status_code{rpc_svc="{{ .Release.Name }}-rpc.{{ .Release.Namespace }}"}
          >= 300
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "The RPC svc for {{ .Release.Name }}-rpc.{{ .Release.Namespace }} is down."
        description: "Service {{ .Release.Name }}-rpc in namespace {{ .Release.Namespace }} has been down for the last 5 minutes."
{{- end -}}
{{- end -}}
