{{- if and .Values.publishSnapshot.enabled .Values.useGatewayAPI -}}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-public-snapshot
  labels:
{{ include "cosmos-operator-rpc-node.commonLabels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.publishSnapshot.pathPrefix }}/{{ .Values.blch.name }}/index.html
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.publishSnapshot.baseDomain }}
spec:
  parentRefs:
  {{- range .Values.gateway.listeners }}
  - name: {{ $.Values.gateway.name }}
    group: gateway.networking.k8s.io
    kind: Gateway
    namespace: {{ $.Values.gateway.namespace }}
    sectionName: {{ . }}
  {{- end }}
  hostnames:
  - {{ .Values.blch.name }}-{{ .Values.blch.network }}-{{ .Values.blch.nodeType }}-snapshots.{{ .Values.endpointsBaseDomain }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Release.Name }}-public-snapshot
      group: ''
      port: 443
      kind: Service
      weight: 1
{{- end -}} 