{{- if .Values.publishSnapshot.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshots-bucket-{{ .Release.Name }}
  labels:
{{ include "cosmos-operator-rpc-node.commonLabels" . | nindent 4 }}
{{- end -}}
