{{- if eq .Values.blch.nodeType "sentry" }}
{{- range $i := until (int .Values.replicas) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-sentry-{{ $i }}
  labels:
    team: "cosmos"
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $i }}
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
  publishNotReadyAddresses: true      
{{- end }}
{{- end }}
