apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "allora-worker.fullname" . }}
  labels:
    {{- include "allora-worker.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: "{{ include "allora-worker.fullname" . }}"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "allora-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "allora-worker.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "allora-worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- range $key, $value := .Values.containers }}
        - name: {{ $key }}
          image: {{ $value.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy | default "IfNotPresent" }}
          ports:
            {{- toYaml $value.ports | nindent 12 }}
          {{- if $value.command }}
          command:
            {{- toYaml $value.command | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if $value.envFrom }}
            {{- toYaml $value.envFrom | nindent 12 }}
            {{- end }}
            {{- range $.Values.externalSecrets }}
            - secretRef:
                name: {{ .target.name }}
            {{- end }}
          {{- if $value.volumeMounts }}
          volumeMounts:
            {{- toYaml $value.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if $value.env }}
          env:
            {{- toYaml $value.env | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- range $key, $value := .Values.initContainers }}
        - name: {{ $key }}
          image: {{ $value.image }}
          command: {{- toYaml $value.command | nindent 12 }}
          volumeMounts:
            {{- range $value.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.additionalVolumes }}
        {{- range $key, $value := .Values.additionalVolumes }}
        - name: {{ $key }}
          {{- if $value.hostPath }}
          hostPath:
            path: {{ $value.hostPath.path }}
            type: {{ $value.hostPath.type | default "DirectoryOrCreate" }}
          {{- end }}
          {{- if $value.configMap }}
          configMap:
            name: {{ $value.configMap.name }}
          {{- end }}
          {{- if $value.secret }}
          secret:
            secretName: {{ $value.secret.secretName }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ include "allora-worker.name" . }}
          release: {{ .Release.Name }}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
